/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 50724
 Source Host           : localhost:3306
 Source Schema         : TCC

 Target Server Type    : MySQL
 Target Server Version : 50724
 File Encoding         : 65001

 Date: 27/11/2018 14:16:52
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for TCC_TRANSACTION_MERCHANT
-- ----------------------------
DROP TABLE IF EXISTS `TCC_TRANSACTION_MERCHANT`;
CREATE TABLE `TCC_TRANSACTION_MERCHANT`  (
  `TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOMAIN` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `GLOBAL_TX_ID` varbinary(32) NOT NULL,
  `BRANCH_QUALIFIER` varbinary(32) NOT NULL,
  `CONTENT` varbinary(8000) NULL DEFAULT NULL,
  `STATUS` int(11) NULL DEFAULT NULL,
  `TRANSACTION_TYPE` int(11) NULL DEFAULT NULL,
  `RETRIED_COUNT` int(11) NULL DEFAULT NULL,
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime(0) NULL DEFAULT NULL,
  `VERSION` int(11) NULL DEFAULT NULL,
  `IS_DELETE` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`TRANSACTION_ID`) USING BTREE,
  UNIQUE INDEX `UX_TX_BQ`(`GLOBAL_TX_ID`, `BRANCH_QUALIFIER`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for TCC_TRANSACTION_ORDER
-- ----------------------------
DROP TABLE IF EXISTS `TCC_TRANSACTION_ORDER`;
CREATE TABLE `TCC_TRANSACTION_ORDER`  (
  `TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOMAIN` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `GLOBAL_TX_ID` varbinary(32) NOT NULL,
  `BRANCH_QUALIFIER` varbinary(32) NOT NULL,
  `CONTENT` varbinary(8000) NULL DEFAULT NULL,
  `STATUS` int(11) NULL DEFAULT NULL,
  `TRANSACTION_TYPE` int(11) NULL DEFAULT NULL,
  `RETRIED_COUNT` int(11) NULL DEFAULT NULL,
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime(0) NULL DEFAULT NULL,
  `VERSION` int(11) NULL DEFAULT NULL,
  `IS_DELETE` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`TRANSACTION_ID`) USING BTREE,
  UNIQUE INDEX `UX_TX_BQ`(`GLOBAL_TX_ID`, `BRANCH_QUALIFIER`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for TCC_TRANSACTION_PRODUCT
-- ----------------------------
DROP TABLE IF EXISTS `TCC_TRANSACTION_PRODUCT`;
CREATE TABLE `TCC_TRANSACTION_PRODUCT`  (
  `TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOMAIN` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `GLOBAL_TX_ID` varbinary(32) NOT NULL,
  `BRANCH_QUALIFIER` varbinary(32) NOT NULL,
  `CONTENT` varbinary(8000) NULL DEFAULT NULL,
  `STATUS` int(11) NULL DEFAULT NULL,
  `TRANSACTION_TYPE` int(11) NULL DEFAULT NULL,
  `RETRIED_COUNT` int(11) NULL DEFAULT NULL,
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime(0) NULL DEFAULT NULL,
  `VERSION` int(11) NULL DEFAULT NULL,
  `IS_DELETE` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`TRANSACTION_ID`) USING BTREE,
  UNIQUE INDEX `UX_TX_BQ`(`GLOBAL_TX_ID`, `BRANCH_QUALIFIER`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
