server:
  port: 9009

spring:
  application:
    name: product-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yunaxiaozhou1
    url: jdbc:mysql://localhost:3306/PRODUCT?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    hikari:
      maximum-pool-size: 20
  aop:
    proxy-target-class: true

tcc:
  datasource:
    url: jdbc:mysql://localhost:3306/TCC?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: yunaxiaozhou1
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: info
    com.allen.capital.dao: debug
